version: 2
jobs:
  build_bleeding_edge:
    docker:
      - image: archlinux

    steps:
      - checkout

      - run:
          name: Install required tools
          command: 'pacman -Sy --noconfirm base base-devel gcc git cmake'
      - run:
          name: Run CMake
          command: 'mkdir build ; cd build ; cmake .. -D CMAKE_BUILD_TYPE=Debug -D CMAKE_BUILD_BENCHMARKS=ON -D CMAKE_BUILD_PROFILER=ON'
      - run:
          name: Compile
          command: 'cmake --build build'
      - run:
          name: Execute test suite
          command: 'cd build ; ctest --output-on-failure -j 2'

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - build_bleeding_edge:
          filters:
            branches:
              ignore:
                gh-pages
