DOXYFILE = 'Doxyfile-mcss'
FAVICON = 'favicon/favicon.ico'
MAIN_PROJECT_URL = 'https://taskflow.github.io'
#HTML_EXTRA_STYLESHEET = ['taskflow.css']
VERSION_LABELS = True
FINE_PRINT = """<p>Taskflow handbook is part of the <a href="https://taskflow.github.io">Taskflow project</a>, copyright © <a href="https://tsung-wei-huang.github.io/">Dr. Tsung-Wei Huang</a>, 2018&ndash;2023.<br />Generated by <a href="https://doxygen.org/">Doxygen</a> {doxygen_version} and <a href="https://mcss.mosra.cz/">m.css</a>.</p>"""
LINKS_NAVBAR1 = [
  ("Handbook", 'pages', []),
  ("Namespaces", 'namespaces', [])
]
